package com.sil.asset_tagging_system.model.enums;

public enum HistoryAction {
    ASSET_INITIAL_REGISTRATION,
    CUSTODY_ALLOCATED,
    ASSET_REQUESTED,
    ASSET_REQUEST_APPROVED,
    ASSET_REQUEST_REJECTED,
    TRANSFER_REQUESTED,
    PEER_TRANSFER_COMPLETED,
    TRANSFER_REJECTED,
    RETURN_REQUESTED,
    RETURN_COMPLETED,
    RETURN_REJECTED,
    STATUS_REPORT_DAMAGE,
    STATUS_CHANGED_TO_MAINTENANCE,
    MAINTENANCE_COMPLETED,
    ASSET_RETIRED,
    ASSET_UPDATED
}
